#!/bin/bash

##SBATCH -N 1

##SBATCH --ntasks-per-node=10

module purge
module load intel_parallel_studio_xe_2015
module load python-2.7.3
export OPENCL_VENDOR_PATH="/opt/intel/intel"

#module load gcc-4.8.1

python measurements.py


